assignmentProject/Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace assignmentProject.Models
{
    public class Actor
    {

        //actor property
        [Key,ScaffoldColumn(false)]
        public int ActorID { get; set; }

        [Required, StringLength(150), Display(Name = "FirstName")]
        public string ActorFName { get; set; }

        [Required, StringLength(150), Display(Name = "LastName")]
        public string ActorLName { get; set; }
        // one actor have many movies
        public virtual ICollection<Movie> Movies { get; set; }
    }
}

assignmentProject/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using assignmentProject.Models;
using assignmentProject.Models.ViewModels;
using System.Diagnostics;


namespace assignmentProject.Controllers
{    /*reference from class example*/
    public class ActorController : Controller
    {
        private MovieCMSContext db = new MovieCMSContext();

        // GET: Actor
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public ActionResult List()
        {

            IEnumerable<Actor> actors = db.Actors.ToList();
            return View(actors);
        }
        //get : create actor
        public ActionResult New()
        {


            ActorEdit actoreditview = new ActorEdit();
            return View(actoreditview);
        }


        [HttpPost]
        public ActionResult New(string ActorFName_New, string ActorLName_New)
        {
            // Basic query   
            string query = "insert into actors (ActorFName, ActorLName) values (@FirstName, @LastName)";
            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@FirstName", ActorFName_New);
            myparams[1] = new SqlParameter("@LastName", ActorLName_New);


            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }



        public ActionResult Edit(int id)
        {
            //For edit we need a list of actors 


            ActorEdit actoreditview = new ActorEdit();

            actoreditview.actor = db.Actors.Find(id);

            return View(actoreditview);
        }
        [HttpPost]
        public ActionResult Edit(int id, string ActorFName, string ActorLName)
        {
            //If the ID doesn't exist or the actor doesn't exist
            if ((id == null) || (db.Actors.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "update actors set ActorFName=@FirstName, ActorLName=@LastName where actorid=@id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@FirstName", ActorFName);
            myparams[1] = new SqlParameter("@LastName", ActorLName);
            myparams[2] = new SqlParameter("@id", id);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("Show/" + id);
        }
        public ActionResult Show(int? id)
        {
            //If the id doesn't exist or the actor doesn't exist
            if ((id == null) || (db.Actors.Find(id) == null))
            {
                return HttpNotFound();

            }
            string query = "select * from actors where actorid=@id";

            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);


            Actor myactor = db.Actors.SqlQuery(query, myparams).FirstOrDefault();
            return View(myactor);
        }
        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Actors.Find(id) == null))
            {
                return HttpNotFound();

            }
            // delete associated movies
            string query = "delete from Movies where actor_ActorID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);

            // delete actor
            query = "delete from Actors where actorid=@id";
            param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);
            return RedirectToAction("List");
        }



    }
}

assignmentProject/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using assignmentProject.Models;
using assignmentProject.Models.ViewModels;
using System.Diagnostics;

namespace assignmentProject.Controllers
{    /*Reference from class example*/
    public class MovieController : Controller
    {
        private MovieCMSContext db = new MovieCMSContext();

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }
        public ActionResult New()
        {

            return View(db.Actors.ToList());
        }
        [HttpPost]
        public ActionResult New(string MovieNameNew, int? MovieActorNew)
        {
            string query = "insert into Movies (MovieName, actor_ActorID) " +
                "values (@name,@aid)";

            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@name", MovieNameNew);
            myparams[1] = new SqlParameter("@aid", MovieActorNew);

            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }
        public ActionResult Show(int id)
        {
            string query = "select * from movies where movieid =@id";
            return View(db.Movies.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }
        public ActionResult Edit(int? id)
        {

            MovieEdit movieedit = new MovieEdit();
            movieedit.movie = db.Movies.Find(id);
            movieedit.actors = db.Actors.ToList();

            if (movieedit.movie != null) return View(movieedit);
            else return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(string MovieName, int? MovieActor, int? id)
        {
            if ((id == null) || (db.Movies.Find(id) == null))
            {
                return HttpNotFound();

            }

            string query = "update movies set moviename=@name, " +
                "actor_ActorID=@aid where movieid = @id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter();
            myparams[0].ParameterName = "@name";
            myparams[0].Value = MovieName;

            myparams[1] = new SqlParameter();
            myparams[1].ParameterName = "@aid";
            myparams[1].Value = MovieActor;

            myparams[2] = new SqlParameter();
            myparams[2].ParameterName = "@id";
            myparams[2].Value = id;


            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("Show/" + id);
        }
        public ActionResult Delete(int id)
        {
            string query = "delete from Movies where movieid = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            return RedirectToAction("List");
        }

        public ActionResult List()
        {


            return View(db.Movies.ToList());

        }
    }
}

assignmentProject/Views/Actor/Edit.cshtml
@model assignmentProject.Models.ViewModels.ActorEdit
@{
    ViewBag.Title = "Edit";
}
<h2>Edit Actor @Model.actor.ActorFName</h2>

<form method="POST" action="/Actor/Edit/@Model.actor.ActorID">
    <div>
        <label >Actor First Name</label><br/>
        <input type="text" value="@Model.actor.ActorFName" id="ActorFName" name="ActorFName" />
    </div>
    <div>
        <label>Actor Last Name</label><br/>
        <input type="text" value="@Model.actor.ActorLName" id="ActorLName" name="ActorLName" />
    </div><br/>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>

assignmentProject/Views/Actor/List.cshtml
@model IEnumerable<assignmentProject.Models.Actor>
@{
    ViewBag.Title = "List";
}

<h2>List of Actors:</h2>


<div>
    @Html.ActionLink("Add a New Actor", "New", "Actor")
</div>
<div>
    @foreach (var actor in Model)
    {

        <div>


            <div>
                <label>@Html.ActionLink("Actor Name : " +actor.ActorFName + actor.ActorLName, "Show/" + actor.ActorID)</label>

                @*<p>@actor.ActorLName</p>*@
                <P>My List of Movies   : @actor.Movies.Count()</P>
                <span>
                    @Html.ActionLink("Delete", "Delete/" + actor.ActorID)
                </span>
            </div>
            <div class="clearfix"></div>
        </div>

    }
</div>

assignmentProject/Views/Actor/New.cshtml
@model assignmentProject.Models.ViewModels.ActorEdit
@{
    ViewBag.Title = "New";
}

<h2>Add New Actor Name</h2>

<form method="POST" action="/Actor/New">
    <div>
        <label>Actor First Name</label><br/>
        <input type="text" id="ActorFName_New" name="ActorFName_New" />
    </div>
    <div>
        <label>Actor Last Name</label><br/>
        <input type="text" id="ActorLName_New" name="ActorLName_New" />
    </div><br/>
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>

assignmentProject/Views/Actor/Show.cshtml
@model assignmentProject.Models.Actor
@{
    ViewBag.Title = "Show";
}

<h2>Actor Name :: @Model.ActorFName  @Model.ActorLName</h2>
@*<h2>@Model.ActorLName</h2>*@

<div>

    @Html.ActionLink("Edit", "Edit/" + Model.ActorID)
</div>

<div>

    @Html.ActionLink("Delete", "Delete/" + Model.ActorID)

</div>

<p><b> @Model.ActorFName  @Model.ActorLName </b> : List of Movies</p>

        @foreach (var movie in Model.Movies)
        {
            <span>@Html.ActionLink(movie.MovieName, "Show/" + movie.MovieID, "Movie")</span><br/><br/>
        }

        @Html.ActionLink("Add a movie", "New", "Movie")




        <div>
            <div class="clearfix"></div>
        </div>